const express = require('express');
const { requireAuth } = require('../../middleware/auth');
const Insight = require('../../models/Insight');

const router = express.Router();

// Insights are generated by the nightly/weekly worker (workers/taskInsights.js),
// never on-demand in a request — that keeps this endpoint a cheap read.
router.get('/', requireAuth, async (req, res) => {
  const insights = await Insight.find({ userId: req.user.id }).sort({ periodStart: -1 }).limit(12);
  res.json(insights);
});

module.exports = router;
